name: "Deploy pages"

on:
  push:
    branches:
    - 'master'
  workflow_dispatch:
    inputs:
      reason:
        default: "Manual trigger"

jobs:
  Build-n-Deploy:
    name: Build and deploy Lektor websites
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v7
      - name: Install uv
        uses: astral-sh/setup-uv@v10.0.1
        with:
          enable-cache: true
      - name: Install dependencies
        run: |
          uv sync --locked --group search
          uv pip list
      - name: Deploy
        env:
          ABOUT_SSH_PRIVATE_KEY: ${{ secrets.ABOUT_SSH_PRIVATE_KEY }}
          BLOG_SSH_PRIVATE_KEY: ${{ secrets.BLOG_SSH_PRIVATE_KEY }}
          HELP_SSH_PRIVATE_KEY: ${{ secrets.HELP_SSH_PRIVATE_KEY }}
        run: uv run --no-sync ./rundeploy.sh
